### ISSUE TITLE
yarn add gatsby-source-notion-databse-private Notfound

### ISSUE THREAD

**Issue by Difers** [superman66/gatsby-starter-notion#1]
作者您好，我在执行yarn add gatsby-source-notion-databse-private 出现 Notfound，如下：

![image](https://user-images.githubusercontent.com/10421743/93196943-9de19200-f77d-11ea-9565-f6e40028a8a0.png)

**Comment by chaos2171053** [comment]
@Difers node.js版本需要 "^10.17.0 || ^12.0.0 || >= 13.7.0"
